version: "3.3"
services:
  # MySQL
  # db:
  #   image: mariadb:10.5.8
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: "belajarbahasaarab"
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: "user"
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: "0dPoimgtUh8LfKZ"
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: "0dPoimgtUh8LfKZ"
  #   ports:
  #     # <Port exposed> : <MySQL Port running inside container>
  #     - "3306:3306"
  #   expose:
  #     # Opens port 3306 on the container
  #     - "3306"
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql
  # # Names our volume
  # volumes:
  #   my-db:

  # Postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=belajar-bahasa-arab
